bot:
  properties:
    token: 984320629:AAHPR4dMzD8O21hNzW4aOERbVkXIEapZTio
    botName: teams-tv telegram bot
    path: .
    downloadButton: Загрузить на сервер
    captionButton: Добавить описание
    cancelButton: Отменить загрузку
    cleanUpTimeOut: 20