bot:
  properties:
    token: token
    name: teams-tv telegram bot
    path: .
    downloadButName: Загрузить на сервер
    addCaption: Добавить описание
    cancelButton: Отменить загрузку
    cleanUpTimeOut: 20
