bot:
  properties:
    token: 740572402:AAHLQLD5XG_KadYJVJjuadlJrO1eESKikpU
    name: teams-tv telegram bot
    path: .
    downloadButton: Загрузить на сервер
    captionButton: Добавить описание
    cancelButton: Отменить загрузку
    repoProps:
      storePath: C:\\tmp
      flushDelay: 300
      cleanDelay: 3000