bot:
  properties:
    token: token
    botName: teams-tv telegram bot
    path: /home/pi/teamstv/teams_tv_server/static/img/events
    downloadButton: Загрузить
    captionButton: Описание
    cancelButton: Отменить
    deleteButton: Удалить
    transferServiceCapacity: 128