bot:
  properties:
    token: 984320629:AAHPR4dMzD8O21hNzW4aOERbVkXIEapZTio
    botName: teams-tv telegram bot
    path: .
    downloadButton: Загрузить
    captionButton: Описание
    cancelButton: Отменить
    deleteButton: Удалить
    transferServiceCapacity: 4